pipeline {
    agent any 

    parameters {
        separator(name: 'CONFIG', sectionHeader: 'Configuração')
        
        choice(name: 'AWS_PROFILE', choices: ['default', 'dev-profile', 'prod-profile'], description: 'Profile AWS do Agente')
        choice(name: 'OPERATION_MODE', choices: ['FULL_MIGRATION', 'BACKUP_ONLY', 'RESTORE_ONLY'], description: 'Modo')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'Região AWS')
        
        separator(name: 'CLUSTERS', sectionHeader: 'Clusters')
        string(name: 'CLUSTER_SOURCE_NAME', defaultValue: '', description: 'Cluster ORIGEM')
        string(name: 'CLUSTER_DEST_NAME', defaultValue: '', description: 'Cluster DESTINO')
        
        separator(name: 'VELERO', sectionHeader: 'Velero')
        string(name: 'VELERO_BUCKET_NAME', description: 'Bucket S3')
        string(name: 'VELERO_ROLE_ARN', description: 'Role ARN')
        
        separator(name: 'EXTRA', sectionHeader: 'Extras')
        string(name: 'BACKUP_NAME_TO_RESTORE', defaultValue: '', description: 'Backup ID (Só para Restore Only)')
        string(name: 'ISTIO_SYNC_MODE', defaultValue: 'all', description: "Istio Sync")
        
        // CLEANUP_ENABLED removido da interface
    }

    stages {
        stage('Dependências') {
            steps {
                sh 'pip3 install boto3 kubernetes requests --user || true'
            }
        }

        stage('Migração') {
            steps {
                sh 'python3 -u migracao_jenkins.py'
            }
        }
    }
}
